### ISSUE TITLE
Uplink internet connection

### ISSUE THREAD

**Issue by jhilden** [railscamp/railscamp-germany-2013#34] opened 2013-06-19 10:05 UTC
We nee somebody to talk to all the companies that could help us in getting a decent internet connection to the Abenteuerhalle.

Options to check would be:
- [ ] NetCologne (they are supposed to have fiber cable until the end of the street)
- [ ] Telekom (maybe they can provide/sponsor LTE connections?)
- [ ] Unity Media
- [ ] Richtfunk from some company or so in the neighborshood with good internet

There is a separate issue #9 dealing with setting up the local wifi, that has a lot of additional useful information.

**Comment by moonglum** [comment] 2013-06-22 17:28
Contacted Stephan again (he didn't answer the email last time) to ask, how they managed to get Telekom LTE for the conference. Will keep you posted.

**Comment by timbuchwaldt** [comment] 2013-06-24 19:43
Will someone contact one of the providers? I mean... LTE might be okayish - but for that our WiFi system is a overkill :D

**Comment by jhilden** [comment] 2013-06-25 06:26
@namxam could you do that? Today? Was @koos able to get you a contact at netcologne?

**Comment by timbuchwaldt** [comment] 2013-06-25 08:16
I just remembered: As we use the CCCMZ WiFi system, we can only support **two** uplink routers. So if we go with LTE, we are limited in regards of uplink routers. (Or if we bundle DSL uplinks, which could also work)

**Comment by koos** [comment] 2013-06-26 08:19
If you need it - we've bought 3 of those http://www.amazon.de/gp/product/B00CTIKXR6/ref=oh_details_o03_s00_i00?ie=UTF8&psc=1
Just give me a shout.

On Jun 25, 2013, at 10:16 AM, Tim Buchwaldt notifications@github.com wrote:

> I just remembered: As we use the CCCMZ WiFi system, we can only support two uplink routers. So if we go with LTE, we are limited in regards of uplink routers. (Or if we bundle DSL uplinks, which could also work)
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by raucao** [comment] 2013-06-26 09:00
Nice.

**Comment by timbuchwaldt** [comment] 2013-06-26 11:33
@koos Thanks :) We got the big package by CCCMZ, which uses the pro-version of the APs, which are not quite compatible. But if we find the usecase, we will let you know (wrong issue, btw :D )

**Comment by koos** [comment] 2013-06-27 09:03
okay
On Jun 26, 2013, at 1:33 PM, Tim Buchwaldt notifications@github.com wrote:

> @koos Thanks :) We got the big package by CCCMZ, which uses the pro-version of the APs, which are not quite compatible. But if we find the usecase, we will let you know (wrong issue, btw :D )
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by moonglum** [comment] 2013-06-29 07:45
From Stephan Maihöfer:

> Der Kontakt bei der Telekom ist inzwischen nicht mehr da, Johannes höhrt
> sich aber nochmal um. Er sagt auch, zitat:
> 
>   "guter ansprechpartner ist auch der 4010 Shop auf der Ehrenstrasse,
>    da bin ich damals einfach rein und hab nachgefragt .."
> 
> sollte sich doch noch ein direkterer kontakt auftun, melde ich mich nochmal.

**Comment by koos** [comment] 2013-06-29 17:09
ich habe noch einen guten kontakt zur telekom.
kann ich helfen?

On Jun 29, 2013, at 9:45 AM, Lucas Dohmen notifications@github.com wrote:

> From Stephan Maihöfer:
> 
> Der Kontakt bei der Telekom ist inzwischen nicht mehr da, Johannes höhrt
> sich aber nochmal um. Er sagt auch, zitat:
> 
> "guter ansprechpartner ist auch der 4010 Shop auf der Ehrenstrasse,
> da bin ich damals einfach rein und hab nachgefragt .."
> 
> sollte sich doch noch ein direkterer kontakt auftun, melde ich mich nochmal.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by moonglum** [comment] 2013-06-30 10:07
Wer hatte denn jetzt den Internet-Hut, der @timbuchwaldt ? :smile:

**Comment by jhilden** [comment] 2013-06-30 11:20
Nobody in particular wanted to put on the the "internet hat" and I can't blame people for that.

This is currently probably the most difficult and **most important** organizational task that we have for Railscamp, we need all the help we can get from anybody.  I will personally see that anybody who can help us get a somwhat decent internet connection to the Abenteuerhalle, will get all the recognition he/she deserves and more.

@koos yes please, we need that contact at the Telekom.  Contacting the contact would be even more awesome.

**Comment by jhilden** [comment] 2013-07-03 07:17
Status update:
- We contacted @koos's contacts at the Telekom startup incubator, but since we are a developer event they didn't feel responsible.
- I contacted NetCologne (who owns the Anschluss at the venue) and the key account manager of the Jugendenzentren Köln _Herr Wölk_ is supposed to get back to me about possible ways of beefing up the existing Kupferleitung.  But even if this should all be possible, which is far from certain, we probably won't be able to ge more than a couple of Mbit out of that connection I guess.

Can anybody else please try to contact the Telekom or Vodafone about potential LTE connections?  Maybe @seanlilmateus can ask again?  That would be really awesome!  Or @namxam?

**Comment by jhilden** [comment] 2013-07-04 11:14
I got answer from NetCologne and they said that we definitely won't get more than 4 Mbit bandwith out of the connection at the venue.  Theoretically one could do something with SDSL to get 20 Mbit, but the price for that would go into the thousands, and 20 Mbit isn't that much either for 200 people.  :cry:

**Comment by moonglum** [comment] 2013-07-04 12:13
Oh shit :crying_cat_face:
I guess the only option is LTE then, isn't it?

**Comment by koos** [comment] 2013-07-04 12:23
I already ordered 3 seperate telephone lines.
jfyi
On Jul 4, 2013, at 2:13 PM, Lucas Dohmen notifications@github.com wrote:

> Oh shit 
> I guess the only option is LTE then, isn't it?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by timbuchwaldt** [comment] 2013-07-04 13:26
Please keep in mind: we need a special router then that bundles the uplink.

**Comment by raucao** [comment] 2013-07-06 13:09
> I already ordered 3 seperate telephone lines.

@koos What does that mean exactly? That we don't need to get something else? We need to know details asap, if we have to bundle lines etc.

**Comment by koos** [comment] 2013-07-07 22:29
We should have a backup. I'll call Netcologne tomorrow and ask about the progress.

On Jul 6, 2013, at 3:09 PM, Sebastian Kippe notifications@github.com wrote:

> I already ordered 3 seperate telephone lines.
> 
> What does that mean exactly? That we don't need to get something else? We need to know details asap, if we have to bundle lines etc.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* Visit Cologne for a one week hack-tech-biz-creativity festival this year! June 17th - 23rd. http://interactive-cologne.com **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by jhilden** [comment] 2013-07-08 05:14
I have called viprinet on Friday (they sponsor the evoke and organize the
internet for that event) and maybe they will be able to help us.

I also contacted Vodafone about LTE and they are supposed to call me back
by tomorrow.

Also contacted the Telekom Hotline and they told me to got to a T-Punkt
store and ask there, maybe something could be possible with LTE Testkarten.
 Would anybody be able to do that?  It would need to happen soon.

**Comment by jhilden** [comment] 2013-07-09 15:33
I got an reply from Vodafone and it seems unlikely that we will be able to get something from them, because they don't offer rented short-term LTE as a product, but they forwarded our request from their sales to the marketing department.

**Comment by DonSchado** [comment] 2013-07-10 17:11
Ich war gerade bei dem 4010 Telekom Laden auf der Ehrenstraße.
Der Typ meinte grundsätzlich müsste das auch in 2 Wochen realisierbar sein, da Internet hinzubekommen. 
Sponsoring fand er interessant und klärt das mit dem Vertrieb ab.
Hab ihm alle Eckdaten und meine Kontaktdaten da gelassen, die wollen sich (angeblich) morgen bei mir melden.

Wir werden sehen...

**Comment by raucao** [comment] 2013-07-11 09:25
You da man!

**Comment by moonglum** [comment] 2013-07-13 21:23
@DonSchado Und? Was neues? :smile:

**Comment by DonSchado** [comment] 2013-07-14 07:06
Nope :( will da nochmal jemand hinfahren?

**Comment by DonSchado** [comment] 2013-07-15 07:56
Rufe gleich da an und berichte...

edit: jo, muss einer hinfahren, Telefon können die nicht...

**Comment by DonSchado** [comment] 2013-07-16 16:43
War gerade da. Telekom/4010 is durch. 
Der Kerl hat mich voll abgespeist:

"Hier gibt's nur Verträge, n Kontakt nach Bonn haben wir hier nicht... wenn sich bisher keiner bei ihnen gemeldet hat, können wir ihnen da wohl nicht helfen..."

Sollen's mal über die Mobilefunk-Business Hotline versuchen: 0800-3302828

Naja, hat sonst noch jemand noch ne Idee? :)

**Comment by moonglum** [comment] 2013-07-16 17:10
AFAIK the two things left are:
1. Tividoo: Crazy expensive. I don't know if this fits our budget.
2. Richtfunk: I don't know what the status is on that?

I think we should really start building up a Plan b. I suggested setting up a Ruby Gems Mirror (via [rubygems-mirror](https://github.com/rubygems/rubygems-mirror) and [geminabox](https://github.com/geminabox/geminabox)) plus Git(lab – maybe plus Gitlab CI) server. @timbuchwaldt really liked the idea and volunteered to set it up. We now only need a server for that. It's not an alternative to an internet connection, but rather something to make slow / no internet less painful.

**Comment by cice** [comment] 2013-07-17 09:29
maybe put the ruby core docs and rails api docs on that server too

**Comment by schnittchen** [comment] 2013-07-17 09:46
Twitter-bootstrap maybe?

**Comment by thegcat** [comment] 2013-07-17 09:47
What about completely forgetting about Internet at the venue and providing a gem mirror, some docs, a gitlab or whatever and just the network so that people can connect between themselves if needed. For proper access to internet: most people probably have a data plan already, that should be enough for the rest (it would probably be enough for me at least).

**Comment by bumi** [comment] 2013-07-17 10:10
I personally think internet is overrated. It is great to have and all the effort everybody has put into this is just amazing. :heart:  
If it is not possible, I think it's fine. we had great events without internet and even the internet sucked at the best conferences so much that it was pretty much not existing. - (yeah I know we do not have a conference... ;) )
As Felix said, most of the people have 3G and if they need to lookup some documentation or download something it will somehow be possible.

**Comment by DonSchado** [comment] 2013-07-17 10:18
For API Documentation on OSX I recommend Dash: https://itunes.apple.com/de/app/dash-docs-snippets/id458034879?mt=12 ;)

For anything else too large for 3G plans, 
we maybe can setup a "Internet-gas-station", where ~5 ppl can connect over ethernet?

@railsbros-dirk and @tisba come up with this idea I think. (Ah or was it @koos ?)

**Comment by tisba** [comment] 2013-07-17 10:27
Good luck with 3G when 100+ people around you are trying do use it ;)

@bumi I think it is not very fair not telling paying participants of a hacking event that there will be no internet connection. some might not really care, but some might be. Personally, when I know that there is no internet around, can prepare myself and still have a good time hacking things. But knowingly withholding this information would _really_ piss me off to be honest.

@DonSchado no, not my/our idea.

**Comment by jhilden** [comment] 2013-07-17 10:41
@tisba message ist out https://twitter.com/railscamp_de/status/357446522570412032 PLZ RT

**Comment by tisba** [comment] 2013-07-17 10:44
@jhilden totally missed that, sorry. is there a way to reach all participants by email?

**Comment by koos** [comment] 2013-07-17 10:52
@sebastian - you're not paying for having internet you're paying for
everything else that make this event unique. And it will be - even without
internet. I agree to bumi. Lets focus on other things from now.

**Comment by eimann** [comment] 2013-07-17 11:04
Have you asked the Koelner Studentenwerk? They should be located in sight of the Abenteuerhallen building, if that's the case and they're giving you an Ethernet port I'm able to sponsor you appropiate equipment for the weekend.

**Comment by raucao** [comment] 2013-07-17 11:04
@koos You just mentioned https://github.com/sebastian instead of the one you meant. ;)

Anyway, it looks like the paid-for LTE will even be within our budget if all goes well.

**Comment by eimann** [comment] 2013-07-17 11:05
The FH Koeln is also next to the Studentenwerk, maybe ask some of their Computer Science students, if they have any?

**Comment by bumi** [comment] 2013-07-17 11:05
@tisba totally agree! and this event is one of the most open and collaborative events that I know. note is already out. what else could be communicated?

**Comment by raucao** [comment] 2013-07-17 11:07
@eimann Can you find out if there's a direct line of sight to the Abenteuerhallen?

**Comment by eimann** [comment] 2013-07-17 11:26
@skddc it should work, even without a direct line of sight (trees are ok, buildings not so much), it's roughly 1.5km. I just don't have a contact at the FH yet who can arrange an Ethernet-Port + rooftop access.

![railscamp-rifu](https://f.cloud.github.com/assets/2742432/811414/9398c10c-eed3-11e2-88f8-5757cfbee134.png)

**Comment by tisba** [comment] 2013-07-17 11:28
@koos of course. The issue is that internet connectivity for such an event in cologne is taken for granted. I'm just saying it should be made clear to everyone beforehand so that they can decide if it is okay for them or not.

@bumi I missed the announcement on twitter and the blog (didn't even noticed before that there is a blog) and a couple of others I know off missed it to.

Long story short: It looks like I am the only one participating in this issue who thinks that having internet connectivity will assumed by most participants, so I'll shut up and hope for the best.

**Comment by bumi** [comment] 2013-07-17 11:32
I've contacted [QSC](http://www.qsc.de/) (also of Barcamp Cologne 1 fame), but I don't have much hope that they are able to support us. 

@tisba no, I guess not that's why this is such a long issue and everyone is trying to fix it :)

**Comment by raucao** [comment] 2013-07-17 11:34
That wi-fi connection looks doable, and universities have proper uplinks. This could be gold!

How do we proceed?

**Comment by eimann** [comment] 2013-07-17 11:37
I'm just trying to figure out whom to contact there. And as @bumi QSC might be an option too, it should be in reach for their Wireless Local Loop product. I've asked a contact there if it's possible and how long they need to get it up & running.

**Comment by thegcat** [comment] 2013-07-17 12:10
(Just a note about @tisba s comment: _should_ the internet still be problematic or off the table on monday, I strongly vote in favor of informing the participants _directly_/via e-mail of this so they can take appropriate measures)

**Comment by raucao** [comment] 2013-07-17 12:19
Go, @eimann, go! :D

**Comment by klaustopher** [comment] 2013-07-17 12:24
Agreeing with @thegcat here. A blog post and a tweet containing a "cry for help" with the internet issue is not a clear communication to the attendees that there might be limited to no internet connectivity. If I hadn't looked at the issues here I wouldn't know that this might be an issue and I think a lot of people just bought a ticket without checking in here.

**Comment by raucao** [comment] 2013-07-17 12:28
Everybody calm down, please! There _will_ be Internet at venue. The question is only how fast exactly and how expensive it'll be.

We also just received word from the LTE/router provider that it's going to be much cheaper to set up than what the first offer was.

**Comment by koos** [comment] 2013-07-17 12:36
I'm also working on getting it from my friend or from the trash chic via
richtantennen. #jfyi

**Comment by jhilden** [comment] 2013-07-17 21:51
Since it seems not unlikely that we might be able to get some sort of guerilla Richtfunk connection in place on way or the other,  where exactly do we get the equipment from?  Form Berlin @thilo ?   Or from the CCC where we get the wifi equipment @timbuchwaldt ?   Or @eimann you said you would able to "sponsor appropiate equipment for the weekend" ?   Please get back to me on how this could happen and what the capabilities of the equipment are.

Besides that it's final that we will get a 6 port Viprinet router/bundler from http://tividoo.eu.  It is equipped with 2 LTE modules (Vodafone with 10GB data inclusive & Telekom with 5GB inclusive) and after that it is unfortunately 8,50€/GB.  It also has 2 DSL modules and 2 ethernet modules for potential Richtfunk.

**Comment by eimann** [comment] 2013-07-17 22:58
@jhilden we will sponsor Router + 2x 65cm dishes with radio module each (up to 30km with line of sight, 100Mbps), a /22 IPv4 network and a /48 IPv6 network via that router

**Comment by jhilden** [comment] 2013-07-18 08:48
@eimann awesome.  You're the man!   What company should I put on the sponsors page of our website?

Now we only have to find a place to set it up, but we are on it and maybe more people can help as well.  When could you & the equipment be in Cologne next week?  Friday morning would be good.

**Comment by eimann** [comment] 2013-07-18 09:43
@badboy and myself will be in Cologne on 26th at 1100 (or earlier, but I don't think this will work due to traffic)

**Comment by koos** [comment] 2013-07-18 16:28
Hey. Short update: I've contacted one of the Prof's from FH-Köln. He will contact some other persons and/or the Campus IT to figure out how if we can solve the problem. This is how it could looks like http://goo.gl/maps/MtRgt
He will come back to me on this tomorrow.

**Comment by badboy** [comment] 2013-07-23 14:09
@koos Anything new on that? Would be good to have a contact person on friday.

**Comment by raucao** [comment] 2013-07-23 14:27
Yeah, would be great to have a backup uplink, and it seems like this is very doable and there's already contact with the right people. Maybe he can give us email addresses or phone numbers of the IT dept?

**Comment by badboy** [comment] 2013-07-23 14:53
If we don't have a contact over there, who will give us access to the roof, it wouldn't make sense for us to come all the way to cologne (and I could stay in the pool the whole friday :sunny: :swimmer: )

**Comment by jhilden** [comment] 2013-07-23 15:18
We have visited the FH's IT department today, but it didn't seem very likely that they want to help us.   Rooftop access shouldn't be a problem, but if they don't give us the necessary access to their network it doesn't look so good.

**Comment by koos** [comment] 2013-07-24 08:57
First feedback from FH-Köln: they are able to support us.

On Jul 23, 2013, at 5:18 PM, Jakob Hilden notifications@github.com wrote:

> We have visited the FH's IT department today, but it didn't seem very likely that they want to help us. Rooftop access shouldn't be a problem, but if they don't give us the necessary access to their network it doesn't look so good.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Jan Kus

Railslove GmbH
An der Bottmühle 5, 50678 Cologne, Germany  

Mobile +49 (0) 179 13 53 53 9
Twitter @koos

Registergericht: Amtsgericht Köln, HRB 70843  
Geschäftsführer: Michael Bumann, Jan Kus, Tim Schneider

*\* We're proud of building: http://dealbaseapp.com - a web based deal tracking and portfolio management tool **

*\* this email brought to you by ✓ http://instantcheckmark.com ✓ **

**Comment by raucao** [comment] 2013-07-24 10:26
\o/

**Comment by eimann** [comment] 2013-07-26 10:29
We succeeded, @railscamp does have working Internet now.

**Comment by moonglum** [comment] 2013-07-26 10:31
You rock!! :rocket:

**Comment by raucao** [comment] 2013-07-26 10:58
What @moonglum said!

**Closed as completed by raucao** 2013-07-26 10:58 UTC
Labels: venue

**Comment by badboy** [comment] 2013-07-26 11:04
\o/ :smile:
